import { Conversation, Lead, Message } from '@/types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    customerName: 'Sarah Johnson',
    customerInitials: 'SJ',
    channel: 'instagram',
    lastMessage: "Yes, I'd like to order 2 pieces in size M",
    lastMessageTime: '2m ago',
    intent: 'Order',
    intentCount: 2,
    isActive: true,
    messages: [
      {
        id: 'm1',
        conversationId: '1',
        content: 'Hi! I saw your post about the summer collection',
        timestamp: '10:24 AM',
        isFromCustomer: true,
      },
      {
        id: 'm2',
        conversationId: '1',
        content: 'Hello Sarah! Yes, we have amazing pieces. What caught your eye?',
        timestamp: '10:25 AM',
        isFromCustomer: false,
      },
      {
        id: 'm3',
        conversationId: '1',
        content: 'The floral midi dress in the second slide',
        timestamp: '10:26 AM',
        isFromCustomer: true,
      },
      {
        id: 'm4',
        conversationId: '1',
        content: "Great choice! It's one of our bestsellers. We have it in sizes S, M, and L. The price is $89.",
        timestamp: '10:27 AM',
        isFromCustomer: false,
      },
      {
        id: 'm5',
        conversationId: '1',
        content: "Yes, I'd like to order 2 pieces in size M",
        timestamp: '10:28 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '2',
    customerName: 'Mike Anderson',
    customerInitials: 'MA',
    channel: 'instagram',
    lastMessage: 'What colors do you have available?',
    lastMessageTime: '15m ago',
    intent: 'Query',
    intentCount: 1,
    messages: [
      {
        id: 'm6',
        conversationId: '2',
        content: 'What colors do you have available?',
        timestamp: '10:10 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '3',
    customerName: 'Emma Davis',
    customerInitials: 'ED',
    channel: 'instagram',
    lastMessage: 'Thanks! Looking forward to it',
    lastMessageTime: '1h ago',
    intent: 'Order',
    messages: [
      {
        id: 'm7',
        conversationId: '3',
        content: 'Thanks! Looking forward to it',
        timestamp: '9:25 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '4',
    customerName: 'Alex Chen',
    customerInitials: 'AC',
    channel: 'instagram',
    lastMessage: 'Can you send more photos of the blue ...',
    lastMessageTime: '2h ago',
    intent: 'Lead',
    messages: [
      {
        id: 'm8',
        conversationId: '4',
        content: 'Can you send more photos of the blue jacket?',
        timestamp: '8:25 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '5',
    customerName: 'Jessica Brown',
    customerInitials: 'JB',
    channel: 'whatsapp',
    lastMessage: 'Do you ship internationally?',
    lastMessageTime: '3h ago',
    intent: 'Query',
    messages: [
      {
        id: 'm9',
        conversationId: '5',
        content: 'Do you ship internationally?',
        timestamp: '7:25 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '6',
    customerName: 'David Martinez',
    customerInitials: 'DM',
    channel: 'messenger',
    lastMessage: "Perfect! I'll take it",
    lastMessageTime: '5h ago',
    intent: 'Order',
    messages: [
      {
        id: 'm10',
        conversationId: '6',
        content: "Perfect! I'll take it",
        timestamp: '5:25 AM',
        isFromCustomer: true,
      },
    ],
  },
  {
    id: '7',
    customerName: 'Rachel Green',
    customerInitials: 'RG',
    channel: 'messenger',
    lastMessage: 'Is this still available?',
    lastMessageTime: '6h ago',
    intent: 'Query',
    messages: [
      {
        id: 'm11',
        conversationId: '7',
        content: 'Is this still available?',
        timestamp: '4:25 AM',
        isFromCustomer: true,
      },
    ],
  },
];

export const mockLeads: Record<string, Lead> = {
  '1': {
    id: 'lead1',
    conversationId: '1',
    name: 'Sarah Johnson',
    initials: 'SJ',
    channel: 'instagram',
    intent: 'Order',
    status: 'Hot Lead',
    orders: 3,
    lastReply: '2m ago',
    leadValue: 267.0,
    notes: 'Customer interested in summer collection. Prefers size M. Follow up after sending photos.',
  },
  '2': {
    id: 'lead2',
    conversationId: '2',
    name: 'Mike Anderson',
    initials: 'MA',
    channel: 'instagram',
    intent: 'Query',
    status: 'New Lead',
    orders: 0,
    lastReply: '15m ago',
    leadValue: 0,
    notes: '',
  },
  '3': {
    id: 'lead3',
    conversationId: '3',
    name: 'Emma Davis',
    initials: 'ED',
    channel: 'instagram',
    intent: 'Order',
    status: 'Converted',
    orders: 1,
    lastReply: '1h ago',
    leadValue: 89.0,
    notes: 'Ordered floral dress. First-time customer.',
  },
  '4': {
    id: 'lead4',
    conversationId: '4',
    name: 'Alex Chen',
    initials: 'AC',
    channel: 'instagram',
    intent: 'Lead',
    status: 'Warm Lead',
    orders: 0,
    lastReply: '2h ago',
    leadValue: 0,
    notes: 'Interested in blue jacket. Send more photos.',
  },
  '5': {
    id: 'lead5',
    conversationId: '5',
    name: 'Jessica Brown',
    initials: 'JB',
    channel: 'whatsapp',
    intent: 'Query',
    status: 'New Lead',
    orders: 0,
    lastReply: '3h ago',
    leadValue: 0,
    notes: 'Asking about international shipping.',
  },
  '6': {
    id: 'lead6',
    conversationId: '6',
    name: 'David Martinez',
    initials: 'DM',
    channel: 'messenger',
    intent: 'Order',
    status: 'Hot Lead',
    orders: 2,
    lastReply: '5h ago',
    leadValue: 156.0,
    notes: 'Ready to purchase. Returning customer.',
  },
  '7': {
    id: 'lead7',
    conversationId: '7',
    name: 'Rachel Green',
    initials: 'RG',
    channel: 'messenger',
    intent: 'Query',
    status: 'Cold Lead',
    orders: 0,
    lastReply: '6h ago',
    leadValue: 0,
    notes: 'Checking availability.',
  },
};
