import { Conversation, Message, Lead, Order } from '@/types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    channel: 'instagram',
    customerHandle: 'john_doe_23',
    customerName: 'John Doe',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    lastMessage: 'Hi! Do you have this in size M?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5),
    intent: 'Inquiry',
    unreadCount: 2,
    externalConversationId: 'ig_conv_123',
    externalCustomerId: 'ig_user_456',
  },
  {
    id: '2',
    channel: 'whatsapp',
    customerHandle: '+1234567890',
    customerName: 'Sarah Wilson',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    lastMessage: 'When will my order be delivered?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    intent: 'Delivery',
    unreadCount: 0,
    isVIP: true,
    externalConversationId: 'wa_conv_789',
    externalCustomerId: '+1234567890',
  },
  {
    id: '3',
    channel: 'messenger',
    customerHandle: 'Mike Seller',
    customerName: 'Mike Seller',
    profilePicture: 'https://randomuser.me/api/portraits/men/67.jpg',
    lastMessage: 'I want to place an order for 3 items',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    intent: 'Order',
    unreadCount: 1,
    externalConversationId: 'fb_conv_321',
    externalCustomerId: 'fb_user_654',
  },
  {
    id: '4',
    channel: 'instagram',
    customerHandle: 'fashion_lover_21',
    customerName: 'Emma Johnson',
    profilePicture: 'https://randomuser.me/api/portraits/women/17.jpg',
    lastMessage: 'Is this available in blue?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    intent: 'Inquiry',
    unreadCount: 0,
  },
  {
    id: '5',
    channel: 'whatsapp',
    customerHandle: '+9876543210',
    customerName: 'Priya Sharma',
    profilePicture: 'https://randomuser.me/api/portraits/women/63.jpg',
    lastMessage: 'Can I get a discount on bulk orders?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 4),
    intent: 'Inquiry',
    unreadCount: 3,
    isVIP: true,
    externalConversationId: 'wa_conv_456',
    externalCustomerId: '+9876543210',
  },
  {
    id: '6',
    channel: 'messenger',
    customerHandle: 'alex_styles',
    customerName: 'Alex Thompson',
    profilePicture: 'https://randomuser.me/api/portraits/men/22.jpg',
    lastMessage: 'Thanks for the quick response!',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 5),
    intent: 'Issue',
    unreadCount: 0,
    externalConversationId: 'fb_conv_999',
    externalCustomerId: 'fb_user_888',
  },
  {
    id: '7',
    channel: 'instagram',
    customerHandle: 'trendy_boutique',
    customerName: 'Rachel Green',
    profilePicture: 'https://randomuser.me/api/portraits/women/28.jpg',
    lastMessage: 'Do you ship internationally?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 6),
    intent: 'Inquiry',
    unreadCount: 1,
  },
  {
    id: '8',
    channel: 'whatsapp',
    customerHandle: '+1122334455',
    customerName: 'David Kim',
    profilePicture: 'https://randomuser.me/api/portraits/men/45.jpg',
    lastMessage: 'My order arrived damaged. Please help.',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 7),
    intent: 'Issue',
    unreadCount: 2,
  },
  {
    id: '9',
    channel: 'messenger',
    customerHandle: 'lisa_marie_shop',
    customerName: 'Lisa Marie',
    profilePicture: 'https://randomuser.me/api/portraits/women/35.jpg',
    lastMessage: 'I love the new collection! 😍',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 8),
    intent: 'Inquiry',
    unreadCount: 0,
    isVIP: true,
  },
  {
    id: '10',
    channel: 'instagram',
    customerHandle: 'style_hunter_99',
    customerName: 'Chris Martinez',
    profilePicture: 'https://randomuser.me/api/portraits/men/52.jpg',
    lastMessage: 'What payment methods do you accept?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 10),
    intent: 'Inquiry',
    unreadCount: 0,
  },
  {
    id: '11',
    channel: 'whatsapp',
    customerHandle: '+5544332211',
    customerName: 'Nina Patel',
    profilePicture: 'https://randomuser.me/api/portraits/women/56.jpg',
    lastMessage: 'Can I return the item if it doesnt fit?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 12),
    intent: 'Issue',
    unreadCount: 1,
  },
  {
    id: '12',
    channel: 'messenger',
    customerHandle: 'urban_wear_fan',
    customerName: 'Jake Wilson',
    profilePicture: 'https://randomuser.me/api/portraits/men/76.jpg',
    lastMessage: 'Placed the order. When will it ship?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 14),
    intent: 'Delivery',
    unreadCount: 0,
  },
  {
    id: '13',
    channel: 'instagram',
    customerHandle: 'fashionista_2024',
    customerName: 'Mia Chen',
    profilePicture: 'https://randomuser.me/api/portraits/women/79.jpg',
    lastMessage: 'Are these handmade?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 16),
    intent: 'Inquiry',
    unreadCount: 0,
  },
  {
    id: '14',
    channel: 'whatsapp',
    customerHandle: '+6677889900',
    customerName: 'Omar Hassan',
    profilePicture: 'https://randomuser.me/api/portraits/men/83.jpg',
    lastMessage: 'I need to change my delivery address',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 18),
    intent: 'Issue',
    unreadCount: 4,
  },
  {
    id: '15',
    channel: 'messenger',
    customerHandle: 'the_style_guru',
    customerName: 'Sophie Brown',
    profilePicture: 'https://randomuser.me/api/portraits/women/90.jpg',
    lastMessage: 'Do you have a loyalty program?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 20),
    intent: 'Inquiry',
    unreadCount: 0,
    isVIP: true,
  },
];

export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversationId: '1',
      senderId: 'john_doe_23',
      text: 'Hey! I saw your post about the new collection',
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      isFromCustomer: true,
      channel: 'instagram',
    },
    {
      id: 'm2',
      conversationId: '1',
      senderId: 'seller',
      text: 'Hi! Thanks for reaching out. Yes, we just launched it!',
      timestamp: new Date(Date.now() - 1000 * 60 * 8),
      isFromCustomer: false,
      channel: 'instagram',
    },
    {
      id: 'm3',
      conversationId: '1',
      senderId: 'john_doe_23',
      text: 'Hi! Do you have this in size M?',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      isFromCustomer: true,
      channel: 'instagram',
    },
  ],
  '2': [
    {
      id: 'm4',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Hi, I ordered 2 T-shirts and a cap last week',
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4b',
      conversationId: '2',
      senderId: 'seller',
      text: 'Hello Sarah! Yes, I can see your order. It was shipped yesterday.',
      timestamp: new Date(Date.now() - 1000 * 60 * 42),
      isFromCustomer: false,
      channel: 'whatsapp',
    },
    {
      id: 'm4c',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Great! Do you have the tracking number?',
      timestamp: new Date(Date.now() - 1000 * 60 * 40),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4d',
      conversationId: '2',
      senderId: 'seller',
      text: 'Yes! Your tracking number is TRK123456789. You can track it on the courier website.',
      timestamp: new Date(Date.now() - 1000 * 60 * 38),
      isFromCustomer: false,
      channel: 'whatsapp',
    },
    {
      id: 'm4e',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Thank you so much! 🙏',
      timestamp: new Date(Date.now() - 1000 * 60 * 35),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4f',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'When will my order be delivered?',
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
  ],
  '3': [
    {
      id: 'm5',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'Hey there! I love your products',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 10),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5b',
      conversationId: '3',
      senderId: 'seller',
      text: 'Thank you Mike! We appreciate the support. How can I help you today?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 8),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5c',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'I saw the hoodie collection on your page. Are they still available?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 5),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5d',
      conversationId: '3',
      senderId: 'seller',
      text: 'Yes! We have all sizes in stock. Would you like me to send you the catalog?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 3),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5e',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'That would be great! Also, do you offer bulk discounts?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 1),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5f',
      conversationId: '3',
      senderId: 'seller',
      text: 'Absolutely! For orders of 3 or more items, we offer 15% off.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 + 1000 * 60 * 1),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5g',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'I want to place an order for 3 items',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      isFromCustomer: true,
      channel: 'messenger',
    },
  ],
  '4': [
    {
      id: 'm6',
      conversationId: '4',
      senderId: 'fashion_lover_21',
      text: 'Is this available in blue?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
      isFromCustomer: true,
      channel: 'instagram',
    },
  ],
};

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    channel: 'instagram',
    customerHandle: 'john_doe_23',
    customerName: 'John Doe',
    intent: 'Inquiry',
    status: 'New',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5),
    lastMessageSnippet: 'Hi! Do you have this in size M?',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    notes: 'Interested in size M products',
    conversationId: '1',
  },
  {
    id: 'l2',
    channel: 'whatsapp',
    customerHandle: '+1234567890',
    customerName: 'Sarah Wilson',
    intent: 'Delivery',
    status: 'In Progress',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    lastMessageSnippet: 'When will my order be delivered?',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    linkedOrders: ['o1'],
    conversationId: '2',
  },
  {
    id: 'l3',
    channel: 'messenger',
    customerHandle: 'Mike Seller',
    customerName: 'Mike Seller',
    intent: 'Order',
    status: 'Converted',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    lastMessageSnippet: 'I want to place an order for 3 items',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50),
    linkedOrders: ['o2'],
    conversationId: '3',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    customerId: 'l2',
    customerHandle: '+1234567890',
    amount: 1299,
    status: 'Shipped',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
    items: '2x T-Shirts, 1x Cap',
  },
  {
    id: 'o2',
    customerId: 'l3',
    customerHandle: 'Mike Seller',
    amount: 599,
    status: 'Pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    items: '1x Hoodie',
  },
];
