import { Conversation, Message, Lead, Order } from '@/types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    channel: 'instagram',
    customerHandle: 'john_doe_23',
    customerName: 'John Doe',
    profilePicture: undefined,
    lastMessage: 'Hi! Do you have this in size M?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5),
    intent: 'Inquiry',
    unreadCount: 2,
    externalConversationId: 'ig_conv_123',
    externalCustomerId: 'ig_user_456',
  },
  {
    id: '2',
    channel: 'whatsapp',
    customerHandle: '+1234567890',
    customerName: 'Sarah Wilson',
    lastMessage: 'When will my order be delivered?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    intent: 'Delivery',
    unreadCount: 0,
    isVIP: true,
    externalConversationId: 'wa_conv_789',
    externalCustomerId: '+1234567890',
  },
  {
    id: '3',
    channel: 'messenger',
    customerHandle: 'Mike Seller',
    customerName: 'Mike Seller',
    lastMessage: 'I want to place an order for 3 items',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    intent: 'Order',
    unreadCount: 1,
    externalConversationId: 'fb_conv_321',
    externalCustomerId: 'fb_user_654',
  },
  {
    id: '4',
    channel: 'instagram',
    customerHandle: 'fashion_lover_21',
    customerName: 'Emma Johnson',
    lastMessage: 'Is this available in blue?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    intent: 'Inquiry',
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversationId: '1',
      senderId: 'john_doe_23',
      text: 'Hey! I saw your post about the new collection',
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      isFromCustomer: true,
      channel: 'instagram',
    },
    {
      id: 'm2',
      conversationId: '1',
      senderId: 'seller',
      text: 'Hi! Thanks for reaching out. Yes, we just launched it!',
      timestamp: new Date(Date.now() - 1000 * 60 * 8),
      isFromCustomer: false,
      channel: 'instagram',
    },
    {
      id: 'm3',
      conversationId: '1',
      senderId: 'john_doe_23',
      text: 'Hi! Do you have this in size M?',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      isFromCustomer: true,
      channel: 'instagram',
    },
  ],
  '2': [
    {
      id: 'm4',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Hi, I ordered 2 T-shirts and a cap last week',
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4b',
      conversationId: '2',
      senderId: 'seller',
      text: 'Hello Sarah! Yes, I can see your order. It was shipped yesterday.',
      timestamp: new Date(Date.now() - 1000 * 60 * 42),
      isFromCustomer: false,
      channel: 'whatsapp',
    },
    {
      id: 'm4c',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Great! Do you have the tracking number?',
      timestamp: new Date(Date.now() - 1000 * 60 * 40),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4d',
      conversationId: '2',
      senderId: 'seller',
      text: 'Yes! Your tracking number is TRK123456789. You can track it on the courier website.',
      timestamp: new Date(Date.now() - 1000 * 60 * 38),
      isFromCustomer: false,
      channel: 'whatsapp',
    },
    {
      id: 'm4e',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'Thank you so much! 🙏',
      timestamp: new Date(Date.now() - 1000 * 60 * 35),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
    {
      id: 'm4f',
      conversationId: '2',
      senderId: 'sarah_wilson',
      text: 'When will my order be delivered?',
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
      isFromCustomer: true,
      channel: 'whatsapp',
    },
  ],
  '3': [
    {
      id: 'm5',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'Hey there! I love your products',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 10),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5b',
      conversationId: '3',
      senderId: 'seller',
      text: 'Thank you Mike! We appreciate the support. How can I help you today?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 8),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5c',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'I saw the hoodie collection on your page. Are they still available?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 5),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5d',
      conversationId: '3',
      senderId: 'seller',
      text: 'Yes! We have all sizes in stock. Would you like me to send you the catalog?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 3),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5e',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'That would be great! Also, do you offer bulk discounts?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 1),
      isFromCustomer: true,
      channel: 'messenger',
    },
    {
      id: 'm5f',
      conversationId: '3',
      senderId: 'seller',
      text: 'Absolutely! For orders of 3 or more items, we offer 15% off.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 + 1000 * 60 * 1),
      isFromCustomer: false,
      channel: 'messenger',
    },
    {
      id: 'm5g',
      conversationId: '3',
      senderId: 'mike_seller',
      text: 'I want to place an order for 3 items',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      isFromCustomer: true,
      channel: 'messenger',
    },
  ],
  '4': [
    {
      id: 'm6',
      conversationId: '4',
      senderId: 'fashion_lover_21',
      text: 'Is this available in blue?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
      isFromCustomer: true,
      channel: 'instagram',
    },
  ],
};

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    channel: 'instagram',
    customerHandle: 'john_doe_23',
    customerName: 'John Doe',
    intent: 'Inquiry',
    status: 'New',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5),
    lastMessageSnippet: 'Hi! Do you have this in size M?',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    notes: 'Interested in size M products',
    conversationId: '1',
  },
  {
    id: 'l2',
    channel: 'whatsapp',
    customerHandle: '+1234567890',
    customerName: 'Sarah Wilson',
    intent: 'Delivery',
    status: 'In Progress',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    lastMessageSnippet: 'When will my order be delivered?',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    linkedOrders: ['o1'],
    conversationId: '2',
  },
  {
    id: 'l3',
    channel: 'messenger',
    customerHandle: 'Mike Seller',
    customerName: 'Mike Seller',
    intent: 'Order',
    status: 'Converted',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    lastMessageSnippet: 'I want to place an order for 3 items',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50),
    linkedOrders: ['o2'],
    conversationId: '3',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    customerId: 'l2',
    customerHandle: '+1234567890',
    amount: 1299,
    status: 'Shipped',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
    items: '2x T-Shirts, 1x Cap',
  },
  {
    id: 'o2',
    customerId: 'l3',
    customerHandle: 'Mike Seller',
    amount: 599,
    status: 'Pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    items: '1x Hoodie',
  },
];
